CREATE TABLE cats (
  _id INTEGER PRIMARY KEY,
  name  TEXT COLLATE NOCASE,
  preset INTEGER DEFAULT 0
);
--
CREATE TABLE entries (
  _id INTEGER PRIMARY KEY,
  uuid TEXT,
  cat INTEGER,
  title TEXT COLLATE NOCASE,
  maker INTEGER,
  price TEXT COLLATE NOCASE,
  location TEXT COLLATE NOCASE,
  date INTEGER,
  rating REAL,
  notes TEXT COLLATE NOCASE,
  UNIQUE(uuid) ON CONFLICT FAIL
);
--
CREATE TABLE entries_extras (
  _id INTEGER PRIMARY KEY,
  entry INTEGER,
  extra INTEGER,
  value TEXT COLLATE NOCASE,
  UNIQUE(entry, extra) ON CONFLICT REPLACE
);
--
CREATE TABLE entries_flavors (
  _id INTEGER PRIMARY KEY,
  entry INTEGER,
  flavor TEXT COLLATE NOCASE,
  value INTEGER,
  pos INTEGER DEFAULT 0
);
--
CREATE TABLE extras (
  _id INTEGER PRIMARY KEY,
  cat INTEGER,
  name TEXT,
  pos INTEGER DEFAULT 0,
  preset INTEGER DEFAULT 0,
  deleted INTEGER DEFAULT 0
);
--
CREATE TABLE flavors (
  _id INTEGER PRIMARY KEY,
  cat INTEGER,
  name TEXT,
  pos INTEGER DEFAULT 0
);
--
CREATE TABLE locations (
  _id INTEGER PRIMARY KEY,
  lat REAL,
  lon REAL,
  name TEXT,
  UNIQUE(lat, lon) ON CONFLICT REPLACE
);
--
CREATE TABLE makers (
  _id INTEGER PRIMARY KEY,
  name TEXT COLLATE NOCASE,
  location  TEXT COLLATE NOCASE,
  UNIQUE(name, location) ON CONFLICT IGNORE
);
--
CREATE TABLE photos (
  _id INTEGER PRIMARY KEY,
  entry INTEGER,
  hash TEXT,
  path TEXT,
  pos INTEGER DEFAULT 0,
  UNIQUE(entry, hash) ON CONFLICT REPLACE
);
